package com.vald3nir.smart_energy.domain.common

const val DEFAULT_VALUE_FOR_MAX_POWER_CONSUMPTION = 2500
const val PERCENTAGE_MAX_VALUE_FOR_NORMAL_POWER_CONSUMPTION = .6f
const val PERCENTAGE_MAX_VALUE_FOR_INTERMEDIARY_POWER_CONSUMPTION = .8f